### ISSUE TITLE
replay_coreutils.sh

### ISSUE THREAD

**Issue by qichang3** [zbchen/FuSE#1]
我在docker中的coreutils-exp目录下运行了并行实验，得到了对应的测试用例，但似乎replay脚本不起作用，拿不到对应的覆盖率信息

**Comment by passengerZ** [comment]
对于coreutils测试集的覆盖率信息，难以用gcov统计实际程序的覆盖率。因为有些程序（例如kill，rm）会修改实际操作系统的状态，导致操作系统崩溃（实际上已经崩溃过一次，服务器上所有数据都没了），所以要用 {klee-2.3-float或者smse}/build/bin/klee-stats 对生成的测试用例目录进行操作，例如：

```
/home/aaa/smse/build/bin/klee-stats   /home/aaa/coreutils-exp/bcfiles/
```

在命令行可以获得所有测试用例的 ICov(指令覆盖率) 和 BCov(基本块覆盖率) 结果

**Comment by qichang3** [comment]
非常感谢！建议在readme中更新关于这部分的简单说明

**Comment by qichang3** [comment]
您好，通过klee-stats虽然可以获取诸如ICov、BCov等信息，但似乎难以获得精确到源代码行级别的覆盖信息，这种覆盖信息通常是利用gcov这样的工具插桩统计得到的。在fuse的replay_coreutils.sh中，似乎也是采用这样的思路：先用klee-replay重放测试用例运行被gcov插桩生成的可执行文件echo，然后获取其中的覆盖率信息进行统计。
我尝试测试klee-replay能否重放一个简单的echo测试用例，发现了一些错误：
`root@d3f976d30e92:/home/aaa/coreutils-exp# ../klee-2.3-float/build/bin/klee-replay /home/aaa/coreutils-6.11/obj-gcov/src/echo  bcfiles/echo_output/test000001.ktest 
KLEE-REPLAY: NOTE: Test file: bcfiles/echo_output/test000001.ktest
KLEE-REPLAY: NOTE: Arguments: "/home/aaa/coreutils-6.11/obj-gcov/src/echo" 
KLEE-REPLAY: NOTE: Storing KLEE replay files in /tmp/klee-replay-ubpx1Z
KLEE-REPLAY: NOTE: Creating file /tmp/klee-replay-ubpx1Z/A of length 30
link: No such file or directory`
如果方便的话，非常希望能和您进一步交流这方面的问题。
我的联系方式是：
email: a1341898685@gmail.com
phone: 13956647665
微信：wqc13956647665
欢迎随时联系我
